# Generated by Django 2.2.10 on 2020-05-06 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_number', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=30)),
                ('project_location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('division', models.CharField(max_length=20)),
                ('market_sector', models.CharField(max_length=40)),
                ('discipline', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('link_file', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_number', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=30)),
                ('project_location', models.CharField(max_length=100)),
                ('market_sector', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
