# Generated by Django 3.0.4 on 2020-06-25 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=30)),
                ('project_location', models.CharField(max_length=100)),
                ('market_sector', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number')),
            ],
        ),
        migrations.CreateModel(
            name='Project_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number')),
            ],
        ),
        migrations.CreateModel(
            name='Market_sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('division', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('link_file', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project_number', chained_model_field='project_number', on_delete=django.db.models.deletion.CASCADE, to='ll.Client')),
                ('market_sector', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project_number', chained_model_field='project_number', on_delete=django.db.models.deletion.CASCADE, to='ll.Market_sector')),
                ('memo', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project_number', chained_model_field='project_number', on_delete=django.db.models.deletion.CASCADE, to='ll.Memo')),
                ('project_location', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project_number', chained_model_field='project_number', on_delete=django.db.models.deletion.CASCADE, to='ll.Project_location')),
                ('project_name', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='project_number', chained_model_field='project_number', on_delete=django.db.models.deletion.CASCADE, to='ll.Project_name')),
                ('project_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='project_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ll.Project_number'),
        ),
    ]
