# Generated by Django 2.2.10 on 2020-05-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='p_project_name',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='ll.Project'),
        ),
    ]
