# Generated by Django 3.0.4 on 2020-06-25 22:35

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0002_auto_20200625_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='memo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='project_number', chained_model_field='project_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='ll.Memo'),
        ),
    ]
