# Generated by Django 3.0.4 on 2020-06-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0003_auto_20200625_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
