# Generated by Django 2.2.10 on 2020-05-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0003_auto_20200506_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='ll.Project'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='market_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketsector', to='ll.Project'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectlocation', to='ll.Project'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectnumber', to='ll.Project'),
        ),
    ]
