# Generated by Django 2.2.10 on 2020-05-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0004_auto_20200506_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='client',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='market_sector',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_number',
            field=models.CharField(max_length=10),
        ),
    ]
