# Generated by Django 3.0.4 on 2020-06-26 02:16

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0004_auto_20200625_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_name',
            new_name='Marketsector',
        ),
        migrations.RenameModel(
            old_name='Project_location',
            new_name='Projectlocation',
        ),
        migrations.RenameModel(
            old_name='Market_sector',
            new_name='Projectname',
        ),
        migrations.RenameModel(
            old_name='Project_number',
            new_name='Projectnumber',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='link_file',
            new_name='linkfile',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RenameField(
            model_name='marketsector',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RenameField(
            model_name='projectlocation',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RenameField(
            model_name='projectname',
            old_name='project_number',
            new_name='projectnumber',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='market_sector',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.AddField(
            model_name='lesson',
            name='marketsector',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', default=1, on_delete=django.db.models.deletion.CASCADE, to='ll.Marketsector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='projectlocation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', default=1, on_delete=django.db.models.deletion.CASCADE, to='ll.Projectlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='projectname',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', default=1, on_delete=django.db.models.deletion.CASCADE, to='ll.Projectname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='client',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='projectnumber', chained_model_field='projectnumber', on_delete=django.db.models.deletion.CASCADE, to='ll.Client'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='memo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='projectnumber', chained_model_field='projectnumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='ll.Memo'),
        ),
    ]
