# Generated by Django 2.2.10 on 2020-06-08 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ll', '0007_auto_20200608_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='project_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='project_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectnumber', to='ll.Project'),
        ),
    ]
